heat_set:
  target:
    entity:
      integration: eight_sleep
      domain: sensor
  fields:
    duration:
      required: true
      selector:
        number:
          min: 0
          max: 28800
          unit_of_measurement: seconds
    target:
      required: true
      selector:
        number:
          min: -100
          max: 100
          unit_of_measurement: "°"
heat_increment:
  target:
    entity:
      integration: eight_sleep
      domain: sensor
  fields:
    target:
      required: true
      selector:
        number:
          min: -100
          max: 100
          unit_of_measurement: "°"
side_off:
  target:
    entity:
      integration: eight_sleep
      domain: sensor
side_on:
  target:
    entity:
      integration: eight_sleep
      domain: sensor
away_mode_start:
  target:
    entity:
      integration: eight_sleep
      domain: sensor
away_mode_stop:
  target:
    entity:
      integration: eight_sleep
      domain: sensor