name: hassfest Validation

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - beta
  pull_request:
    branches:
      - main
      - beta
  schedule:
    - cron: '0 1 * * *'

jobs:
  validate:
    name: hassfest Validation
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v3"
        - uses: "home-assistant/actions/hassfest@master"